### ISSUE TITLE
deploy on express server

### ISSUE THREAD

**Issue by unpseudocomplique** [antfu/vite-plugin-pwa#144]
Hi, 
can't mange to make the plugins work with express as a server.

here is a test repo: [https://github.com/unpseudocomplique/test-express-server](https://github.com/unpseudocomplique/test-express-server)

### Steps to reproduce to NOT make it work:
```
yarn
yarn build
yarn start
```

### Steps to reproduce to make it work:
Replace vite build by vite-ssg build and :
```
yarn
yarn build
yarn start
```
I have another question, why in the doc the plugin is installed in the devDependencies. If i push it to the server the building time will have a NODE_ENV=production so it will just crash when we import the package ? I tryed without thinking and yes obiviously it crashed (deployed on clever cloud).

Thanks for your help !

**Comment by userquin** [comment]
@unpseudocomplique sorry but you're using `vitesse` template and so you need `vite-ssg`, the problem is not related to the pwa plugin. 

If you can, just comment out the plugin using `vite` instead `vite-ssg` and you'll see you cannot build your repo; the pwa plugin error will appear since it is a `vite` plugin with `enforce: `post'`, but the root cause is not the plugin, the plugin just throw the error on `vite` build since `vite` will not fail if there are some plugin with `enforce: `post'`.

Just see this line https://github.com/antfu/vite-plugin-pwa/blob/main/src/index.ts#L73 and this entry https://github.com/antfu/vite-plugin-pwa/issues/68#issuecomment-859800287 for an explanation (see the complete issue for context).

Confirm you're using latest version, I don't remember in what version previous issue was fixed.

**Comment by userquin** [comment]
You need to wait a few seconds until the app is cached by the pwa sw, on my laptop takes a few seconds, maybe on your enviroment will take more time.

Using `vite-ssg` will show the server, the server ssr generation, here the ouput with vite:

```shell
F:\work\projects\quini\GitHub\pwa-test-express-server>yarn build && yarn start
yarn run v1.22.10
$ cross-env NODE_ENV=production vite build
vite v2.6.10 building for production...
✓ 91 modules transformed.
dist/index.html                                1.10 KiB
dist/manifest.webmanifest                      0.38 KiB
dist/assets/README.68ad8e20.js                 1.22 KiB / gzip: 0.56 KiB
dist/assets/virtual_pwa-register.932ceed5.js   5.51 KiB / gzip: 2.30 KiB
dist/assets/about.ff65768f.js                  1.78 KiB / gzip: 0.75 KiB
dist/assets/index.9fe4b4b1.js                  23.62 KiB / gzip: 6.93 KiB
dist/assets/[name].44eebaa2.js                 1.66 KiB / gzip: 0.96 KiB
dist/assets/[...all].ff5b47b5.js               0.22 KiB / gzip: 0.19 KiB
dist/assets/404.648e6fdf.js                    0.95 KiB / gzip: 0.56 KiB
dist/assets/home.399c539d.js                   0.40 KiB / gzip: 0.29 KiB
dist/assets/index.f8d73574.css                 17.80 KiB / gzip: 4.27 KiB
dist/assets/vendor.7e65c1aa.js                 114.25 KiB / gzip: 43.80 KiB

PWA v0.11.3
mode      generateSW
precache  17 entries (168.52 KiB)
files generated
  dist\sw.js
  dist\workbox-78503f86.js
Done in 4.76s.
yarn run v1.22.10
$ node index.js
App listening at localhost:8001
```

**Comment by unpseudocomplique** [comment]
I'm sure even after more than 30s there were no popup. More strange the lighthouse test in chrome devtool show that it can't be installed. 
I will try again when i'm at home 🤔.

**Comment by userquin** [comment]
@unpseudocomplique what popup? the `registerType` is `autoUpdate`, you will need to change it on `vite.config.ts` configuration and then add the `ReloadPrompt.vue`, removing the logic from `src/modules/pwa.ts`.

**Comment by userquin** [comment]
@unpseudocomplique read again the docs, `vitesse` template is using `autoUpdate` not `prompt`  on `registerType` so there is no prompt, once detected new version, the app will be auto updated.

If you remove/comment out `registerType`  from pwa plugin configuration and comment out the logic inside `src/modules/pwa.ts`, adding a `ReloadPrompt.vue` component and include it on `src/App.vue`, you still need to change something on some `vue/assets/logic` to create a new sw version and so you will get the prompt for update.

Instead changing vitesse template, just clone this repo and play with `express` on `examples/vue-router` example, similar to `vitesse` template but more basic.

The app cannot be installed since you need to use `https` and the lighthouse will complain on pwa since it is not using `https` and should also redirect from `http` to `https`. If you want to be a `pwa` you will need to use `localhost-https` with `express`, you can see how you can integrate here https://github.com/antfu/vitesse/discussions/169, see Step 2 (you have a link to my branch o my vitesse repo: [server.js](https://github.com/userquin/vitesse/blob/chore/fix-missing-routes-on-sw/server.js)).

**Comment by userquin** [comment]
> 
> 
> I mean the chrome popup to install the pwa like on your documentation

There is no such thing on the docs, you have a prompt for update dialog not for install the pwa: you must click on the navigation bar as shown on previous screenshots for Edge and Chrome.

**Comment by userquin** [comment]
@unpseudocomplique

do you have checked this entry https://vite-plugin-pwa.netlify.app/deployment/#getting-started? Check on network tab on dev tools if all assets are 200 OK, and check if the `manifest.webmanifest` resource content is a JSON and not a string with base 64 encoding. You must check also that on Application tab on Application > Manifest you have the manifest, also on Applciation > Service Worker the sw is installed (should appear with a green dot on activated and running state).

 Using `yarn build && yarn preview-https`:

![imagen](https://user-images.githubusercontent.com/6311119/138169811-715adef5-6c93-4de9-92aa-6d2d29fd8b45.png)

**Comment by userquin** [comment]
@unpseudocomplique not received man: userquin@gmail.com

**Comment by unpseudocomplique** [comment]
Found the issue with a big thanks to @userquin 
SW was not registered with autoUpdate.
Here is a semple: 
```
router.isReady().then(async () => {
    useRegisterSW({ immediate: true })
})
```
