### ISSUE TITLE
Seamless off/online user experience

### ISSUE THREAD

**Issue by mattfysh** [antfu/vite-plugin-pwa#146]
Hi there,

I've just picked up `vite-plugin-pwa` to make my site available offline, however I was wondering if there is a way to offer this functionality without prompting the user, or otherwise giving them any indication to the works of the offline cache?

Ideally, when the user is online, the site would behave like it would without the service worker

And when the user is offline, or there are issues preventing the remote assets from loading, the precached assets are used.

If the user is offline and goes back online, its okay not to update to the latest version until the next full page reload

If the user has multiple tabs open, what happens in one tab shouldn't affect the other, e.g:

1. User is offline and loads up v1 in Tab A
2. User does some work in Tab A, e.g. is filling out a form that interacts with a local storage solution
3. User goes online
4. User opens the site in Tab B, but is now online, so v2 is loaded
5. Tab A is unaffected, so we're left with the user having v1 in Tab A, and v2 in Tab B (an acceptable state)

Cheers!

**Comment by userquin** [comment]
@mattfysh the sw once receives the new version will update all opened clients: tabs, New Windows and also browsers instances.

The sw updates works like browser updates, next time the browser is restarted will install the New version. If you are using prompt for update you will need the user interaction since the sw will be kept on skip waiting state.

This plugin cannot bypass the sw lifecycle.

You can use some strategy with workbox, for example network first or cache first to control the behavior. I think there are some links on the workbox entry on docs.
