### ISSUE TITLE
any way to enable in dev

### ISSUE THREAD

**Issue by sharmapukar217** [antfu/vite-plugin-pwa#200]
what if i have to make changes to my service worker and see that? Do i have to build again and again for each changes?

**Comment by userquin** [comment]
@sharmapukar217 I have a branch on my fork to allow run in dev, but I need to fix some problems reloading the sw using `workbox-window`, it uses some heuristic algoritmh and some events can be wrong. 

The pwa in dev will be disabled, we will only support sw logic and always will force full reload since we cannot use hmr from a service worker yet: dynamic import not allowed.

This week I Will try to add it here.

**Comment by userquin** [comment]
@sharmapukar217 you can see the sw on development in action here https://github.com/jeffposnick/yt-playlist-notifier/issues/2, just check the video linked there on last comment

**Comment by userquin** [comment]
@sharmapukar217 you can now register your service worker in development, version `0.11.13` released, also included some hints on docs.
