### ISSUE TITLE
Needed help with configuring React app with vite-plugin-pwa

### ISSUE THREAD

**Issue by SudhanshuBhagwat** [antfu/vite-plugin-pwa#272]
I have been trying to setup a bare react project without the 2 service worker files mentioned in the guide but haven't been able to do so.
Either the service worker is not correctly generated or the manifest isn't generated at all.
I even tried the react router example, but that doesn't generate the manifest file either.

The following is the link to my working branch: https://github.com/SudhanshuBhagwat/diner/tree/configure-pwa

**Comment by userquin** [comment]
@SudhanshuBhagwat try removing inject register option from the plugin and the link for the manifest on index.htnl

**Comment by userquin** [comment]
Since you are using inject manifest strategy the workbox option on the plugin option will be ignored.

The included assets option is wrong, you should declaee each asset or use some glob dep to list them, such as fast-glob: you can also use the globPattern using injectManifest option on plugin configuration

**Comment by userquin** [comment]
closing this, feel free to open a new issue
