### ISSUE TITLE
Inject manifest.json on development

### ISSUE THREAD

**Issue by darklight9811** [antfu/vite-plugin-pwa#297]
Currently devOptions.enabled only adds a service worker to the development app, add an option to also include the manifest data (manifest.json) would be cool for debugging.

**Comment by userquin** [comment]
@darklight9811 tested on local, PR in a few minutes:

![imagen](https://user-images.githubusercontent.com/6311119/172054345-8be1d310-3a73-40df-9517-acfefe5e7ee9.png)

**Comment by amxmln** [comment]
I’m glad this was merged, but I was very confused by the fact that the docs already mention:

> Since version 0.12.1 the manifest.webmanifest is also served on development mode: you can now check it on dev tools.

when version 0.12.1 isn’t released yet. I was just about to file a new issue that this isn’t working, because I thought it was already released. Is there an ETA for the next release? If not, maybe the docs should be updated to not include the above statement  until the new version is released.
