### ISSUE TITLE
Automatic reload != location.reload?

### ISSUE THREAD

**Issue by bestwestern** [antfu/vite-plugin-pwa#377]
### Describe the bug

If I create new vite simple javascipt project then add vite-plugin-pwa and add vite.config.js:
![image](https://user-images.githubusercontent.com/3617433/190987981-4cc2081f-cf31-4ed1-90ea-9ffa1cfebdce.png)
Then:
Build and deploy (with vercel)
Visit page in browser (and close tab)
Make little change in project
Build and  deploy again
* Visit page again it will show the old version (but under Network I can see the new version being found)
First when I refresh the page it will show the new version.

I was under the impression that a page reload would be made when the new version was found?
If that is not the intent, how do I do it?

PS: this is the generated sw file:
![image](https://user-images.githubusercontent.com/3617433/190988965-ef013560-822c-4c96-acd4-e9ced370578f.png)

### Reproduction

https://github.com/bestwestern/viteplainwithautoupdateerror

### System Info

```Shell
Windows 10
Node v16.17.0
vite: 3.1.0,
vite-plugin-pwa: 0.12.8
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment]
@bestwestern later in the afternoon I take a look at it

**Comment by userquin** [comment]
@bestwestern since you're NOT importing any virtual, there is no way to interact with the UI part of the application, that should fire a page reload: when importing any virtual, the reload is done here https://github.com/antfu/vite-plugin-pwa/blob/main/src/client/build/register.ts#L41 .

You can import the vanilla virtual in your main module, calling the `registerSW` method will fix your problem: 
```ts
import { registerSW } from 'virtual:pwa-register'

registerSW({ immediate: true })
```

**Comment by bestwestern** [comment]
Awesome - it works!
Thanks for the quick reply.

This is what made me believe it would work:
![image](https://user-images.githubusercontent.com/3617433/191316104-b97b0a1f-edc7-4fff-b919-78a7f0c9f2c3.png)

**Comment by userquin** [comment]
@bestwestern thx for the hint, I need to review the code, maybe a regression, I'll change it if not a regression.

**Comment by userquin** [comment]
@bestwestern the automatic reload works, but in the next visit: there are ppl using this way the plugin instead using the virtual.

**Comment by bestwestern** [comment]
Yes - I could see the service worker getting ready for the next visit ;) so I figured maybe it was intentional - that's why I asked the question in the headline of this issue.

Perhaps elaborate in the docs that automatic reload is not a "location reload" :)

**Comment by userquin** [comment]
@bestwestern the problem is the sw lifecycle, the auto update is ok (the sw is activated), but the client requires a page reload to allow the new activated sw to take the control (in the current page, remember the user can have multiple tabs/windows/browser instances opened), that's, the sw isn't controlling yet the current page.

I'll add a warning and danger sections (for Safari users) in the docs just below your hint. I remember issue #33, new browser versions will work (FF and chromium based, except Safari), that's, once the user refresh the page or opens again the browser, the user will have the new app version.
