### ISSUE TITLE
[doc] better explain workbox options for generateSW

### ISSUE THREAD

**Issue by ZYinMD** [antfu/vite-plugin-pwa#87]
As a new user, this part of README is confusing to me:

```js
VitePWA({
  workbox: {
    // workbox options for generateSW
  }
})
```
What are "workbox options"? Could you provide some examples? Thanks!

**Comment by userquin** [comment]
This repo is a wrapper for `workbox` utilities, you can find all the docs on their site:

https://developers.google.com/web/tools/workbox

For `workbox` plugin entry, you can find the docs on node modules entry here:

https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build#.generateSW

You can find type definition here (comes from `workbox-build` module, see import at top):

https://github.com/antfu/vite-plugin-pwa/blob/8605e362dd8bec0ac4449514264ef64753686174/src/types.ts#L77

**Comment by ZYinMD** [comment]
Thanks, then I'd suggest adding one sentence in README to explain that `generateSW` is a workbox term, or at least making it a link like [generateSW](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build#.generateSW). As a new user, 10 minutes of reading the README didn't make me realize that `generateSW` was a workbox term. 

Btw I've used to work with `create-react-app` where you need to import workbox modules and write your sw by hand, but don't need to build it yourself. That's why I've actually read all the workbox docs before, but still don't know what `generateSW` is. There may be many others like me.

**Comment by userquin** [comment]
@ZYinMD I add a new issue to add a small guide (I don't know when it will be added, right now I'm very busy). 

`workbox` is a huge package with a lot of modules to just make service worker development not to be a hassle and avoid dealing with low level service worker api. About workbox modules, there are modules for build and for runtime. 

`generateWS` is a helper module from `workbox-build` to abstract from using `service worker` api when building the service worker. This module can be configured using plugins instead writting your own service worker code (`generateWS` will generate the code for you).

For example, `vite-plugin-pwa` uses `workbox-window` module to build the client side module (`virtual:pwa-register`), while for building target project it uses `workbox-build` to allow using `generateWS` and `injectManifest` strategies (the vite plugin uses  `generateWS` and `injectManifest` from `workbox-build` providing `workbox` and `injectManifest` plugin options respectivelly).

Of course, using this plugin requires little knowledge of service worker stuff, as it is not 100% zero configuration (if you just include `VitePWA()` on `vite.config.ts` file, it will work, but the app will not be a PWA, since it will not meet PWA requirements).

**Comment by userquin** [comment]
@ZYinMD 

You can see how we use `generateWS` and `injectManifest` here: https://github.com/antfu/vite-plugin-pwa/blob/master/src/index.ts#L57.

The problem is that we cannot document each module from `workbox`, you mention `generateWS` but there are a lot of modules on `workbox` and so, why to explain this one and no others?

You can see how we use `workbox-window` for client side module here: https://github.com/antfu/vite-plugin-pwa/blob/master/src/client/build/register.ts.

**Comment by chavda-bhavik** [comment]
@userquin can you say what different kinds of strategies and registerType are available or these strategies also refer to generateSW?

**Comment by userquin** [comment]
@chavda-bhavik 

There are only 3 strategies: `injectManifest` , `generateWS` or none (there is a PR to add a new one: `networkFirst`). The strategies are just a hint for the plugin: if you are generating your own service worker or delegating to build via `generateWS`. The main diference from the plugin perspective, is that we need to `build` the service worker using rollup, and the result of that build is provided to `injectManifest` of `workbox-build`, `injectManifest` will inject the assets entries to the cache.

In the other hand we have the `registerType` that hints the plugin how to register the service worker on the client side and some callbacks to interact with the service worker. There are 2 `registerType` options: `prompt`, `autoUpdate`. 

`registerType` is for (client) runtime while `strategies` is for build-time, both are not directly related: you only need to configure some code when using `injectManifest`, since you are building the service worker while using `generateWS` the plugin will take care for doing for you.

For example, using `injectManifest` you need to add this to make it working with `registerType: 'prompt'` (you also need to configure your app to show the popup calling `registerSW` from `virtual:pwa-register`):
```ts
// see https://github.com/antfu/vite-plugin-pwa/blob/master/examples/vue-basic-inject-manifest/src/sw.ts#L5
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING')
    self.skipWaiting()
})
```
while if you are using `registerType: 'autoUpdate'` you only need these code:
```ts
// see https://github.com/antfu/vite-plugin-pwa/pull/79/files#diff-1febff5dc987ad484a0947d652d6739c8e93bf3abd94fb492165410460feb563
import { clientsClaim } from 'workbox-core'
...
...
self.skipWaiting()
clientsClaim()
```

If you use `prompt` or `autoUpdate` you need to call `registerSW` or `useRegisterSW` (only available for `vue`) from `virtual:pwa-register` or `virtual:pwa-register/vue` respetivelly. See warnings on `README.md`.

Beware if using `injectRegister` plugin option, read the jsdoc here: https://github.com/antfu/vite-plugin-pwa/blob/master/src/types.ts#L37. This option is how the service worker is added to the app. When using `registerSW` or `useRegisterSW` the virtual module just register the service worker via `workbox-window` utilities.
