### ISSUE TITLE
How about add `onRegitered` event  to `registerSW` ?

### ISSUE THREAD

**Issue by myoshi1012** [antfu/vite-plugin-pwa#93]
I'm trying to trigger updates manually like google's document says: https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#manual_updates

At the moment, we can that using [`navigator.serviceWorker.getRegistration`](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/getRegistration) .

```ts
const updateSW = registerSW({
  onNeedRefresh: () => {
    setOpenDialog(true);
  },
});
navigator.serviceWorker.getRegistration('/').then((reg) => {
  // do something
  setInterval(() => {
    reg?.update();
  }, INTERVAL);
});
```

But, if there are `onRegistered` event that has `ServiceWorkerRegistration` argument, be able to become the above code simpler (and safe(?)).

```ts
const updateSW = registerSW({
  onNeedRefresh: () => {
    setOpenDialog(true);
  },
  onRegistered: (reg) => {
    // do something
    setInterval(() => {
      reg?.update();
    }, INTERVAL);
  }
});
```

How about this?

**Comment by userquin** [comment]
Be careful about generating the SW in less than 1 minute: since the workbox uses a `heuristic` calculation to handle SW updates, there could be strange behavior: see https://github.com/antfu/vite-plugin-pwa/pull/94#issuecomment-889940578

I add to the docs how to do it and warn about the 1 minute problem. You can see it [here](https://github.com/antfu/vite-plugin-pwa/blob/f865da57c58d7fafd39a2f4761ef7eff57eace50/README.md#configure-application-to-check-for-service-worker-updates).

**Comment by myoshi1012** [comment]
Noted. Thank you for dealing with it quickly.
